# Generated by Django 5.2.12 on 2026-04-04 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(max_length=300)),
                ('hero_subtitle', models.TextField(blank=True)),
                ('hero_background_image', models.ImageField(blank=True, null=True, upload_to='site/about/')),
                ('intro', models.TextField(blank=True)),
                ('mission_title', models.CharField(default='Our mission', max_length=200)),
                ('mission_body', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About page',
                'verbose_name_plural': 'About page',
            },
        ),
        migrations.CreateModel(
            name='HeroSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(blank=True, default='USA-market software partner', help_text='Small line above the headline.', max_length=160)),
                ('headline', models.CharField(max_length=400)),
                ('subheadline', models.TextField(blank=True)),
                ('background_image', models.ImageField(blank=True, help_text='Full-width hero background (wide image recommended).', null=True, upload_to='site/hero/')),
                ('cta_primary_label', models.CharField(default='Book a Call', max_length=80)),
                ('cta_primary_link', models.CharField(default='/contact', max_length=500)),
                ('cta_secondary_label', models.CharField(blank=True, default='Explore services', max_length=80)),
                ('cta_secondary_link', models.CharField(blank=True, default='/services', max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home — Hero',
                'verbose_name_plural': 'Home — Hero',
            },
        ),
        migrations.CreateModel(
            name='HomePillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Home — Pillar card',
                'verbose_name_plural': 'Home — Pillar cards',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeShowcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='site/home/')),
                ('image_alt', models.CharField(blank=True, max_length=200)),
                ('image_on_right', models.BooleanField(default=False, help_text='If checked, image appears on the right on desktop.')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Home — Showcase block',
                'verbose_name_plural': 'Home — Showcase blocks',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='e.g. "50+" or "99%"', max_length=40)),
                ('label', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Home — Stat',
                'verbose_name_plural': 'Home — Stats',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('category', models.CharField(max_length=120)),
                ('excerpt', models.TextField(help_text='Short text for portfolio cards.')),
                ('body', models.TextField(help_text='Detail page: separate paragraphs with a blank line between them.')),
                ('cover_image', models.ImageField(upload_to='projects/covers/')),
                ('hero_image', models.ImageField(blank=True, help_text='Optional wide image at top of project detail page.', null=True, upload_to='projects/hero/')),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('summary', models.TextField()),
                ('bullets', models.TextField(blank=True, help_text='One bullet per line (shown on Services page).')),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='services/icons/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AboutImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cms.aboutsettings')),
            ],
            options={
                'verbose_name': 'About gallery image',
                'verbose_name_plural': 'About gallery images',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='cms.project')),
            ],
            options={
                'verbose_name': 'Project gallery image',
                'verbose_name_plural': 'Project gallery images',
                'ordering': ['order', 'id'],
            },
        ),
    ]
