# Generated by Django 5.2.12 on 2026-04-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Card / listing image (recommended).', null=True, upload_to='services/covers/'),
        ),
        migrations.AddField(
            model_name='service',
            name='detail',
            field=models.TextField(blank=True, help_text='Detail page: separate paragraphs with a blank line between them.'),
        ),
        migrations.AddField(
            model_name='service',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Optional wide image on the service detail page.', null=True, upload_to='services/hero/'),
        ),
    ]
