# Generated by Django 5.2.12 on 2026-04-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_home_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=320, unique=True)),
                ('description', models.TextField(help_text='Short summary for cards and SEO.')),
                ('bullets', models.TextField(blank=True, help_text='One bullet per line (shown on cards and article intro).')),
                ('body', models.TextField(blank=True, help_text='Full article: separate paragraphs with a blank line between them.')),
                ('cover_image', models.ImageField(blank=True, help_text='Card / header image (recommended).', null=True, upload_to='blog/covers/')),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, help_text='Optional display date on the article.', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Blog post',
                'verbose_name_plural': 'Blog posts',
                'ordering': ['order', '-published_at', '-id'],
            },
        ),
    ]
