# Generated by Django 5.2.12 on 2026-04-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_blog_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('linkedin', 'LinkedIn'), ('x', 'X (Twitter)'), ('facebook', 'Facebook'), ('github', 'GitHub'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('website', 'Website / other')], db_index=True, help_text='Used to pick the icon in the footer.', max_length=20)),
                ('url', models.URLField(max_length=500)),
                ('label', models.CharField(blank=True, help_text='Accessibility name (defaults to the platform name if empty).', max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Social link',
                'verbose_name_plural': 'Social links',
                'ordering': ['order', 'id'],
            },
        ),
    ]
