# Generated by Django 5.2.12 on 2026-04-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_social_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='platform',
            field=models.CharField(choices=[('linkedin', 'LinkedIn'), ('x', 'X (Twitter)'), ('facebook', 'Facebook'), ('github', 'GitHub'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('website', 'Website / other')], db_index=True, help_text='Used to pick the icon in the footer.', max_length=20),
        ),
    ]
